# Generated by Django 5.2.17 on 2026-10-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('last_seen', models.DateTimeField()),
                ('typing_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('room', 'username')},
            },
        ),
    ]
